[application]
k3s_namespace=sdmd
enable_local_testing=Y
enable_log_information_in_table=Y
enable_scaleout_agent=Y
Total_Device_Memory_For_ScaleOut_Threshold_Calculation=8
enable_system_service_metrics_agent=Y
app-name=Systems-Manager
deviceId=25
database_file_path=/src/sqllite.db
device_offline_status_check_enabled=Y
device_online_status_check_frequency=1
device_host_for_health_check=4.240.77.208:1883
device_health_check_topic=device/health/status
asset_manager_url=http://4.240.77.208:8084/
device_offline_data_sync_schedular_frequency=60
device_online_or_offline_status_check_url=http://4.240.77.208:8084/caregiver/getGenders
is_device_offline_sync_required=Y
device_offline_data_sync_device_metrics_topic=device_offline_sync
device_offline_data_sync_device_metrics_client_id=device_metrics_offline_sync_clientId
device_offline_data_sync_service_metrics_topic=service_offline_sync
device_offline_data_sync_service_metrics_client_id=service_metrics_offline_sync_clientId
Cpu_Alert_Threshold=70
Memory_Alert_Threshold=70
Cloud_Systems_Manage_UpdateServiceStatus_URL=http://4.240.77.208:8083/updateServiceStatus

[system_metrics]
is_system_metrics_required=Y
units-cpu=percent
units-memory=GB
units-disk=GB
scheduler_frequency=4
device_offline_sync_batch_size=100


[service_metrics]
is_service_metrics_required=Y
namespace_for_reading_metrics=default
units_cpu=percent
units_memory=GB
units_disk=GB
scheduler_frequency=3
service_offline_sync_batch_size=100

[cloud_configurations]
mqtt_broker_address=98.70.76.149
mqtt_broker_port=1883
device_metrics_client_id=system_manager_device
device_metrics_topic=device_data_demo
service_metrics_client_id=system_manager_service
service_metrics_topic=service_data_demo
prometheus_metrics_url=http://10.0.0.10:32585
config_update_topic=config_update
config_update_client_id=config_update_client


[heart_beat]
is_sensor_heartbeat_required=N
heathypi_heartbeat_brocker_url=4.240.77.208
heathypi_heartbeat_port=1883
heathypi_heartbeat_topic=sensor_heartbeat_topic_device
heathypi_heartbeat_client_id=device_sensor_heartbeat_topic_local_sub_1
cloud_brocker_topic=sensor_heartbeat_topic_cloud
cloud_brocker_client_id=device_sensor_heartbeat_topic_cloud_pub_1

